env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  keyword-spacing:
    - error
    - { before: true, after: true }
  react/jsx-uses-vars:
    - error
